"""add nullable description game

Revision ID: e4e479260b2d
Revises: 2b23e8910097
Create Date: 2024-05-07 19:49:25.984210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4e479260b2d"
down_revision: Union[str, None] = "2b23e8910097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game", "description", existing_type=sa.VARCHAR(length=2048), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game", "description", existing_type=sa.VARCHAR(length=2048), nullable=False
    )
    # ### end Alembic commands ###
