"""add seed data for roles

Revision ID: 6c69fd809fbc
Revises: 
Create Date: 2024-05-03 21:09:38.386440

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c69fd809fbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ... другие операции миграции ...
    # ### end Alembic commands ###

    # ваш код для добавления начальных данных
    role_table = sa.table('role',
                          sa.Column('name', sa.String(16), nullable=False),
                          sa.Column('permission', sa.JSON, nullable=True),
                          sa.Column('created_at', sa.DateTime, nullable=False),  # Ensure to add this line
                          sa.Column('updated_at', sa.DateTime, nullable=False)  # Ensure to add this line
                          )

    current_time = datetime.utcnow()
    op.bulk_insert(role_table,
                   [
                       {'name': 'Admin', 'permission': {'admin': True}, 'created_at': current_time, 'updated_at': current_time},
                       {'name': 'User', 'permission': {'admin': False}, 'created_at': current_time, 'updated_at': current_time},
                       {'name': 'Moderator', 'permission': {'moderate': True}, 'created_at': current_time, 'updated_at': current_time},
                       # ... дополнительные записи ...
                   ]
                   )


def downgrade() -> None:
    pass
